/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AudienceRouteImport } from './routes/_audience'
import { Route as AudienceIndexRouteImport } from './routes/_audience.index'
import { Route as AudienceRecruitmentAgencyRouteImport } from './routes/_audience.recruitment-agency'
import { Route as AudienceEmployersRouteImport } from './routes/_audience.employers'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceRoute = AudienceRouteImport.update({
  id: '/_audience',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceIndexRoute = AudienceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AudienceRoute,
} as any)
const AudienceRecruitmentAgencyRoute =
  AudienceRecruitmentAgencyRouteImport.update({
    id: '/recruitment-agency',
    path: '/recruitment-agency',
    getParentRoute: () => AudienceRoute,
  } as any)
const AudienceEmployersRoute = AudienceEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => AudienceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AudienceIndexRoute
  '/impressum': typeof ImpressumRoute
  '/employers': typeof AudienceEmployersRoute
  '/recruitment-agency': typeof AudienceRecruitmentAgencyRoute
}
export interface FileRoutesByTo {
  '/impressum': typeof ImpressumRoute
  '/employers': typeof AudienceEmployersRoute
  '/recruitment-agency': typeof AudienceRecruitmentAgencyRoute
  '/': typeof AudienceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_audience': typeof AudienceRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/_audience/employers': typeof AudienceEmployersRoute
  '/_audience/recruitment-agency': typeof AudienceRecruitmentAgencyRoute
  '/_audience/': typeof AudienceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impressum' | '/employers' | '/recruitment-agency'
  fileRoutesByTo: FileRoutesByTo
  to: '/impressum' | '/employers' | '/recruitment-agency' | '/'
  id:
    | '__root__'
    | '/_audience'
    | '/impressum'
    | '/_audience/employers'
    | '/_audience/recruitment-agency'
    | '/_audience/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AudienceRoute: typeof AudienceRouteWithChildren
  ImpressumRoute: typeof ImpressumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_audience': {
      id: '/_audience'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_audience/': {
      id: '/_audience/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AudienceIndexRouteImport
      parentRoute: typeof AudienceRoute
    }
    '/_audience/recruitment-agency': {
      id: '/_audience/recruitment-agency'
      path: '/recruitment-agency'
      fullPath: '/recruitment-agency'
      preLoaderRoute: typeof AudienceRecruitmentAgencyRouteImport
      parentRoute: typeof AudienceRoute
    }
    '/_audience/employers': {
      id: '/_audience/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof AudienceEmployersRouteImport
      parentRoute: typeof AudienceRoute
    }
  }
}

interface AudienceRouteChildren {
  AudienceEmployersRoute: typeof AudienceEmployersRoute
  AudienceRecruitmentAgencyRoute: typeof AudienceRecruitmentAgencyRoute
  AudienceIndexRoute: typeof AudienceIndexRoute
}

const AudienceRouteChildren: AudienceRouteChildren = {
  AudienceEmployersRoute: AudienceEmployersRoute,
  AudienceRecruitmentAgencyRoute: AudienceRecruitmentAgencyRoute,
  AudienceIndexRoute: AudienceIndexRoute,
}

const AudienceRouteWithChildren = AudienceRoute._addFileChildren(
  AudienceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AudienceRoute: AudienceRouteWithChildren,
  ImpressumRoute: ImpressumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
